### ISSUE TITLE
JWT section typo

### ISSUE THREAD

**Issue by firthmj** [jonathanthorpe-sony/nmos-authorization-implementers-guide#7]
In section 3.2, the "azp" description has a word that has become "specificen", and the rest of the sentence doesn't follow on from the first half.

Not sure if this is a stack edit corruption, or something else

**Comment by lo-simon** [comment]
It should say:

> The azp claim MUST be included in the token when the client_id is omitted. The azp claim SHOULD NOT be included in the token when the client_id is included in order to minimise token size. This claim is included in order to support Authorization Servers which support the OpenID Connect specification. This claim corresponds with the client identifier of the OAuth 2.0 client that requested the token. The value of this claim MUST exactly match the full client identifier to which the token was granted.


as it is a direct copy from the specs, may be better we should just put the link in the table for those standard claims which are already described in the specs.

**Comment by jonathan-r-thorpe** [comment]
Removed claims already described in specification. Included links to specification instead.
